### ISSUE TITLE
Swagger Markdown Web UI

### ISSUE THREAD

**Issue by shaun-chiang** [syroegkin/swagger-markdown#131]
I've created a quick (hacky) web UI for swagger-markdown for convenience, and it's currently deployed [here](http://swagger-markdown-ui.netlify.com/) (repo [here](https://github.com/shaun-chiang/swagger-markdown-ui)).

Couldn't find @syroegkin's email in his profile, so asking for permission for it to be left up here :)

**Comment by syroegkin** [comment]
Amazing job!
Thank you!
