### ISSUE TITLE
Add support for Tags and Tag Grouping of Paths?

### ISSUE THREAD

**Issue by kevinawoo** [syroegkin/swagger-markdown#188]
Swagger supports grouping `paths` via `tags` https://swagger.io/docs/specification/grouping-operations-with-tags/.

This request is to ask for support for add tag groups as markdown header groupings.

An example output would be something like:
```md
# My Awesome API
## Version 2.0
### Security
security stuff...


### Dogs
These endpoints are dog related endpoints.

#### /list
##### Get
###### Summary
Get all available dogs
###### Description
We'll give a list of all the dogs in the world, paged of course

### Cats
These endpoints are cats related endpoints.

#### /list
##### Get
###### Summary
Get all available cats
###### Description
We'll give a list of all the cats in the world, paged of course
```

This proposed solution would require that:
- Swagger `paths` will need to be grouped by tags (adding 1 layer of nesting)
- When there's no tag grouping, do current behavior (aka, no nesting)

**Comment by syroegkin** [comment]
This is indeed a very nice feature.
I'll take care of it and it shall be included in the v2.0 release.
