### ISSUE TITLE
Edit templates to translate custom fields?

### ISSUE THREAD

**Issue by bc-mkatz** [syroegkin/swagger-markdown#60]
Hello Sergii: Thank you for this script! It works just as described, and yields nice results.

We're now trying to modify the script's templates, to extract and output (with different column headings) some custom fields from our swagger. Would this be as straightforward as editing the `parameters.js` file, writing the edited copy back to our local installation's `package.tgz` archive, and re-running the script?

Or would we need to clone your repo, edit unarchived files, and recompile? Double thanks for any guidance about how to customize the runtime behavior.

**Comment by syroegkin** [comment]
good day. the best way would be to fork it and extend with support of custom fields.

thank you for response.
