### ISSUE TITLE
Reference only parameters are ignored.

### ISSUE THREAD

**Issue by ajkurtz** [syroegkin/swagger-markdown#99]
This is valid swagger 2.0, but parameters specified this way are ignored.

  /{clientId}:
    get:
      description: |
        Get the client.
      parameters:
        - $ref: '#/definitions/clientId'

There is no error when the file is processed, but the Name, Located in, and Description columns in the generated parameters table are blank.

Andy

**Comment by seancsnyder** [comment]
Just started using this library and I'm seeing this as well

**Comment by syroegkin** [comment]
Well not really.
I was trying this with https://editor.swagger.io/ and it always reports about mistake.
It will definitely work when parameters are in parameters section but not in definitions.
So this one will work just fine:
```yaml
swagger: '2.0'
info:
  title: Some API
  description: Some description
  version: "1.0.0"
paths:
  /{clientId}:
    get:
      description: |
        Get the client.
      parameters:
        - $ref: '#/parameters/clientId'
      responses:
        200:
          description: All good

parameters:
  clientId:
    name: clientId
    in: path
    required: true
    type: integer
    format: int32
```
